### ISSUE TITLE
Questions about pangocontext

### ISSUE THREAD

**Issue by raffienficiaud-reasonal** [leifgehrmann/pangocffi#17]
Hi,

First of all, thank you for your work on the pango library, it is really helpful.
I would like to ask about a confusion I currently have concerning the pango context and the cairo context. 

I currently create a `layout` from a context object I have from `cairo`, like this

```
layout = pangocairo.create_layout(context)
```

where

```
import pangocffi as pango
import pangocairocffi as pangocairo
cairo = pangocairo.cairocffi
```

I would like now to set the resolution of the font. The `set_resolution` [here](https://pangocairocffi.readthedocs.io/en/stable/modules.html?highlight=get_resolution#pangocairocffi.set_resolution) applies to a `pangocontext` object. I can create one by using 

```
pangocontext = pangocairo.create_context(cairo_context=context)
```
and then set the resolution like
```
pangocairo.set_resolution(context=pangocontext, dpi=300)
```

* How does this `pangocontext` relate to the layout? I am new to this, and I am not sure to understand how they are linked. Inspecting the code of the library, it looks to me that the layout `__init__` creates each time a new context, and I have not found a way to create the layout with a given pango context.
* how does this pangocontext relate to the cairo context? As I am creating the pango context out of the cairo context, I imagine that they are linked somehow, but does the `set_resolution` call on the pango context impact the cairo context?
* I then later tried this `pangocairo.update_layout(cairo_context=layout.get_context(), layout=layout)` and it makes the application crash (some infinite loop). However `pangocairo.update_layout(cairo_context=context, layout=layout)` works (the passed contexts are different in nature). I am not sure to understand on which type of context the function `update_layout` should be applied.

Sorry if my questions are confused, as I said I am discovering pango and your bindings.

**Comment by leifgehrmann** [comment]
Thanks for taking an interest! I'm not an expert on Pango itself, I mainly needed it to do some basic typesetting for a hobby project of mine a while ago. But I'll try my best to share my understanding of how it fits together!

-----

> How does this pangocontext relate to the layout?

You can see an example here of how to create a layout object, then render the layout object:

https://pangocairocffi.readthedocs.io/en/latest/overview.html#basic-usage-and-example

There are two ways of creating a `Layout` object

1. The long way:
```python
import pangocairocffi
from pangocffi import Layout

pango_context = pangocairocffi.create_context(cairo_context)
layout = Layout(pango_context)
```

2. The slightly quicker way:
```python
import pangocairocffi

layout = pangocairocffi.create_layout(cairo_context)
```

----
> How does this pangocontext relate to the cairo context?

The PangoContext is similar to CairoContext in that it stores the internal state of a system. But they are completely different systems. So just like `cairo_set_source_rgb()` stores the color in cairo's state, the PangoContext has methods that control:

* What fonts are loaded in memory (`pango_context_load_font()`),
* What direction the text should "flow" (`pango_context_set_gravity()`),
* What writing system to use (`pango_context_set_language()`)

I think the only thing that the PangoContext uses from the CairoContext when you call `pangocairocffi.create_context()` is what fonts are loaded. So for example, if Helvetica is loaded as a system font in the CairoContext, the PangoContext will be able to access it. Thankfully, you don't need to worry about loading the fonts yourself as this is handled automatically.

-----

> As I am creating the pango context out of the cairo context, I imagine that they are linked somehow, but does the `set_resolution` call on the pango context impact the cairo context?

I do not think this affects the cairo context itself.

I could be wrong, but I also think `set_resolution` only matters if you are using a [bitmap font](https://en.wikipedia.org/wiki/Computer_font#Bitmap_fonts). Bitmap fonts are generally only used on the display and are not meant for PDFs or printing.

You are probably using [outline fonts](https://en.wikipedia.org/wiki/Computer_font#Outline_fonts) anyway, where you shouldn't need to use `set_resolution`. If you are using an outline font, the renderer will use the best resolution possible on a JPG or PNG surface. If Cairo is rendering on an SVG, PDF, or any other vector based surface, it will actually draw the font as a path, not as a bitmap.

-----

> I then later tried this `pangocairo.update_layout(cairo_context=layout.get_context(), layout=layout)` and it makes the application crash (some infinite loop).

The reason it was crashing was because `pangocairo.update_layout()` expects a CairoContext as the second argument, not a PangoContext, which `layout.get_context()` returns.

You can find out what "types" the functions expect from the documentation: https://pangocairocffi.readthedocs.io/en/latest/modules.html#pangocairocffi.update_layout

----

> Sorry if my questions are confused, as I said I am discovering pango and your bindings.

That's totally understandable! 😄 It took me several weeks to grasp how all the pango and pango-cairo functions related to each other.

But I appreciate the questions. I definitely have wanted to improve the documentation a bit, because a lot of things are still cryptic.

I'm guessing you've seen this already, but in case you haven't, the underlying C functions for pango and pangocairo are described here: https://developer.gnome.org/pango/stable/index.html

You can find information on concepts here:

* `PangoContext`: https://developer.gnome.org/pango/stable/pango-Contexts.html#PangoContext
* `PangoLayout`: https://developer.gnome.org/pango/stable/pango-Layout-Objects.html#PangoLayout-struct
* `PangoCairo` functions: https://developer.gnome.org/pango/stable/pango-Cairo-Rendering.html

And as you might have noticed, quite a lot of methods have not been implemented yet in `pangocffi`. I've only implemented the ones I've needed!

**Comment by raffienficiaud** [comment]
Thanks a lot for your answers! (sorry I replied late)
If I ever manage to understand how pango and cffi work, I would be happy to contribute!

**Comment by leifgehrmann** [comment]
After doing some fresh installs and testing I just realised the code in the [example link](https://pangocairocffi.readthedocs.io/en/latest/overview.html#basic-usage-and-example) I provided was broken 🤦 This probably contributed to the confusion.

I've fixed the code in this commit: https://github.com/leifgehrmann/pangocairocffi/commit/7f869aee461d95d6aa555648964af52709a603f3
