### ISSUE TITLE
Question about "font_description"

### ISSUE THREAD

**Issue by raffienficiaud-reasonal** [leifgehrmann/pangocffi#18]
Hi again,

In order to get a particular font and attach it to the layout, I am doing currently this:

```
font_description_pointer = pangocairo.font_map.pango.pango_font_description_from_string(
        b"Steradian Extralight 25"
    )

font_description = pango.FontDescription.from_pointer(font_description_pointer)
```

and then passing the `font_description` to a `layout`

```
layout.set_font_description(font_description)
```

A couple of question:

* I am pretty sure there is an easier way to achieve this, however I am a bit confused by pango in general. Would you please give me a hint?
* what happens to the pointer `font_description_pointer` after this? Is this garbage collected or should I free it explicitly?

Thank you for your time.

**Comment by leifgehrmann** [comment]
> I am pretty sure there is an easier way to achieve this, however I am a bit confused by pango in general. Would you please give me a hint?

The reason this seems more difficult than it needs to be is because no bindings have been created for this method in the first place 😄. I've personally have not needed to use `FontDescription` yet, but I can imagine it's useful to have this implemented for performance reasons. I think the best thing to do would be to add a new `@classmethod` to `FontDescription` called `from_string(str: string) -> FontDescription` that essentially calls what you have done above.

Alternatively, use `layout.set_markup('<span font="italic 30">Hi from Παν語</span>')` to set the font description (I imagine this is less efficient if you have thousands of layouts to render)

----

> what happens to the pointer font_description_pointer after this? Is this garbage collected or should I free it explicitly?

Good question... I do not think it is GC'd. It appears right now when you call `FontDescription.from_pointer` it calls this method that I made quite a while ago in `pangocffi/font_description.py`...

```python
    def _init_pointer(self, pointer: ffi.CData):
        self._pointer = pointer
        # self._pointer = ffi.gc(pointer, pango.pango_font_description_free)
```

For some reason that last line is commented out.

Not sure what I was thinking at the time... 😅  Perhaps it was crashing for some unrelated reason and I quickly decided not to add the line to free the object when `self._pointer` is dereferenced? Or perhaps I was unsure if ffi.gc was the correct thing to call.

When I have more time to do development I can maybe look into this. But until this is fixed, yes you'll have to wrap the `font_description_pointer` in ffi.gc and apply the `pango_font_description_free` method. Or, use `set_markup` as mentioned above.

**Comment by raffienficiaud** [comment]
Thanks for your answer!
