### ISSUE TITLE
Support Logging

### ISSUE THREAD

**Issue by naveen521kk** [leifgehrmann/pangocffi#26]
Forked from https://github.com/naveen521kk/au-packages

I would like to access the logger of Pango(I think it uses the one from glib) and convert it to things understandable by Python's logger, so that it would be easy to view the DEBUG logs as well as WARNING printed correctly. As in that issue, the font is not there but it doesn't create(or maybe not show) the warning message explicitly as reported by @leotrs . It does shows those messages but it looks like we don't have any control over it. Is it possible to be wrapped around so that our need fulfill?

**Comment by leifgehrmann** [comment]
Using the output of a logger for control-flow seems like a bad idea...

I believe that's what Gnome's documentation suggests as well.

https://developer.gnome.org/glib/stable/glib-Message-Logging.html

> **Testing for Messages**
> [...]
> **Examining the log output of code is discouraged:** libraries should not emit to `stderr` during defined behaviour, and hence this should not be tested. If the log emissions of a library during undefined behaviour need to be tested, they should be limited to asserting that the library aborts and prints a suitable error message before aborting. This should be done with `g_test_trap_assert_stderr()`.
> **If it is really necessary to test the structured log messages emitted by a particular piece of code** – and the code cannot be restructured to be more suitable to more conventional unit testing – **you should write a custom log writer function (see `g_log_set_writer_func()`) which appends all log messages to a queue.** When you want to check the log messages, examine and clear the queue, ignoring irrelevant log messages (for example, from log domains other than the one under test).

As the latter paragraph suggests, it might be possible to create a writer function. But I'm not sure how easy this is to accomplish within CFFI. I can give pointers on how one might accomplish this, but you probably will need to talk someone who is more familiar with python-cffi ([docs](https://cffi.readthedocs.io/en/latest/), [google groups](https://groups.google.com/g/python-cffi?pli=1)).

In general I believe it would be outside of the scope of `pangocffi`, since we are dealing with a different system, `glib`.

-----

I would've suggested that you instead test for the existence of the font via Pango, but I'm not sure how to do this myself right now. Looking at their documentation, it suggests one could do it in the following steps:

1. Use `pango_cairo_font_map_get_default()` to retrieve a `PangoFontMap *`
2. Then use `pango_font_map_list_families(pangoFontMap)` to get a list of `PangoFontFamily ***` objects.
3. Then use `pango_font_family_get_name(pangoFontFamily)` to get the `char *` name of the font family.

Steps 1 and 3 are easy enough to do in CFFI, but I'm not quite sure about step 2. Would need to do some experimentation.

It's also weird that [`PangoFontFamily` is a deprecated struct](https://developer.gnome.org/pango/stable/pango-Fonts.html#PangoFontFamily-struct) that isn't supposed to be used, so it's possible this isn't a viable option either.

-----

Alternatively, you can use Python's Standard library to check for installed fonts, but I'm not sure if the Tk GUI toolkit uses the same way of resolving font-families that Pango does. I'm also not sure if Tk is installed on all Linux ditros, as Tk itself isn't part of the Python Standard library, but [Python.org claims it is on most Unix machines](https://docs.python.org/3/library/tkinter.html).

Below is a snippet of code that I ran that lists all the font-families matching the name 'Courier'.

```
import Tkinter
import tkFont
Tkinter.Tk()
installed_font_families =[i for i in tkFont.families() if 'Courier' in i]
print(installed_font_families)
```

Which outputs:

```
['Courier', 'Courier New']
```

(Although, this also might not be a great solution, since Tk will apparently show an icon in the TaskBar on Mac OS – at least in the test that I did)

**Comment by naveen521kk** [comment]
Sorry for not replying sooner.

I don't exactly know what to do here though. For windows, everything is straight forward on the cmd, but I think that's not the case with, Linux, on reading some of glib docs it looks like there is something more deep on Linux side and not straightforward as windows. Well, I am also closing this, using Tk is not a very good option though.

**Comment by naveen521kk** [comment]
Just to update, I found that this was a bug with Pango itself. https://gitlab.gnome.org/GNOME/pango/-/issues/523
