### ISSUE TITLE
Specify the DLL file to load using Environment Variable

### ISSUE THREAD

**Issue by naveen521kk** [leifgehrmann/pangocffi#27]
I would like to specify exactly what should be the binary to load and not search using `ctypes.util.find_library()` because each time I need to manipulate my PATH variable for this. I would like to a variable PANGO_LOCATION or something similar where I can specify the DLL file to load. This will make sure that there is no python crash because of wrong DLL being loaded. Also, I would use it in Manim so that there is no crash, caused so many issues. If this looks ok then I will make a PR. This would help prevent [DLL HELL](https://en.wikipedia.org/wiki/DLL_Hell).
Same for [`pangocairocffi`](https://github.com/leifgehrmann/pangocairocffi) and [`cairocffi`](https://github.com/Kozea/cairocffi/issues/170) also.
Thanks.

**Comment by leifgehrmann** [comment]
@naveen521kk pangocffi in addition to `pango` uses `glib`, and `gobject`. Am I correct in thinking you will want to specify an environment variable for these DLLs as well?

**Comment by naveen521kk** [comment]
Yeah. I would like to do so. Do you have a better idea?

**Comment by leifgehrmann** [comment]
@naveen521kk Marked as resolved since this is hopefully implemented correctly in v0.9.0. I've also implemented this feature into pangocairocffi (v0.5.0).

This means in total 4 environmental variables can be configured:

* `PANGO_LOCATION`
* `PANGOCAIRO_LOCATION`
* `GLIB_LOCATION`
* `GOBJECT_LOCATION`

Let me know if this works for you!
