### ISSUE TITLE
Using properties instead of getters/setters

### ISSUE THREAD

**Issue by cAttte** [leifgehrmann/pangocffi#44]
hey! first of all, thanks for creating this library, it's been really useful lately.

while using the various interfaces, i noticed that a lot of them use `get_...()` and `set_...()` methods. this is fine, and it makes sense considering the underlying C API, but, IMO, it would be much more pythonic if the library used `property()` instead. something like this:

```py
class Layout(object):
    def set_text(...):
    def get_text(...):
```

could be turned into this, which would simplify the usage and documentation a lot:

```py
class Layout(object):
    def _get_text(...):
    def _set_text(...):
    text = property(_get_text, _set_text)
```

i also see that a lot of the classes use the `@property` decorator instead of the function, which is fine:
```py
class Layout(object):
    @property text
    def get_text(...):
    @text.setter
    def set_text(...):
```

it would be much better if either one of these was (consistently) used across _all_ classes, not just some.

of course, if this change was to be implemented we'd have to keep the original getters/setters for back-compat (unless it was immediately released as a major), and eventually deprecate/underscore them... i'm 100% up for making this change, so just let me know and i'll make a PR!

**Comment by leifgehrmann** [comment]
Hi cAttte, sorry the late reply. And sorry in advance for the lengthy response. 😅 

This is a good idea, but I do have some hesitations.

> while using the various interfaces, i noticed that a lot of them use get_...() and set_...() methods. this is fine, and it makes sense considering the underlying C API

As you hinted, it was done this way so that the setter and getter methods match the C API. I also imitated the [Cariocffi API](https://cairocffi.readthedocs.io/en/stable/api.html#context) which also uses `set_...()` and `get_...()` for handling `Context` and other objects. Since Cairocffi is commonly used with this package I thought it makes sense to follow a similar pattern.

Annoyingly there is also one "property" for the Layout object that breaks the getter/setter pattern. Specifically, the `set_markup()` method for `Layout` has no getter equivalent in [Pango's API](https://docs.gtk.org/Pango/method.Layout.set_markup.html), and actually overrides the `text` and `attributes` properties behind the scenes. So I was conflicted whether to:
  * make the property a setter-only property (which I didn't realise until now [was possible](https://stackoverflow.com/a/50935931)), and have the getter return an AttributeError, which might break user-expectations.
  * or, to avoid confusion, rename the method to something like `apply_markup()` just to suggest that it doesn't behave like a property. The downside of course is discoverability if the developer had some prior knowledge of Pango.
  * or, to keep it simple, keep the name as `set_markup()`. But that would just look awkward.

So this isn't a technical issue, I'm just worried about breaking user expectations. So your thoughts would be highly appreciated on what you feel makes sense. Thankfully I believe this is the only case that exists in Pango, so maybe this isn't such a big deal.

With that all said, I do agree with you though that it would be lovely for this package to be more pythonic. Another contributor made the same suggestion a while back (#34), but I was a bit busy to respond back then and they resolved it fairly quickly, so you are not alone!

> of course, if this change was to be implemented we'd have to keep the original getters/setters for back-compat (unless it was immediately released as a major), and eventually deprecate/underscore them...

Because the package hasn't reached v1 (since full Pango API hasn't been implemented yet, not because it's functionally unstable) I'm comfortable with releasing a breaking change immediately. It's a change that's fairly each to migrate to anyway.

> i'm 100% up for making this change, so just let me know and i'll make a PR!

Yes, I would greatly appreciate it!

I welcome contributions, though I haven't done a good job of writing a CONTRIBUTING.md (I have a rough draft written [here](https://github.com/leifgehrmann/pangocffi/blob/contribution-guidelines/CONTRIBUTING.md) but it doesn't go into enough detail). Even the current requirements.txt is missing a few dependencies (specifically: `setuptools` for basic dev and `sphinx`, `sphinx_rtd_theme` for running `make docs`). Let me know if you do need help setting up the tooling.

**Comment by cAttte** [comment]
don't worry about it, and sorry i didn't see this earlier either!

i was thinking you wouldn't want to implement this for coherence with the Cairo API but i think that if having a nicer interface means sacrificing a little bit of consistency with another library that's totally fine.

after i posted the issue i started refactoring the Layout class a little bit to see how it would look, and i noticed the markup  function you talked about. i don't think we should have it as a setter-only property because as you said, it does more than that, and something like parsing XML within a property assignment feels very wrong (even when we aren't doing it ourselves). i think the same applies to the "setting" notion of a name like `set_markup()`, so, `apply_markup()` feels like the best option — i don't think we would be breaking expectations because every other `get_` and `set_` method will also be removed anyway.

i'll get to making the changes probably this weekend. thank you very much for caring about the library and helping out, and i'll let you know if i have any problems while contributing!

**Comment by leifgehrmann** [comment]
Great!

I'm indifferent on whether it's `@property` or `property()`. I suppose using `@property` would mean a smaller diff, but I like that `property()` clearly ties the setter and getter methods together on one line, so it's up to you!
